<?php

/**
 * @file
 * Contains beignet.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function beignet_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the beignet module.
    case 'help.page.beignet':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('I &lt;3 Beignets') . '</p>';
      return $output;

    default:
  }
}
